import { finalizeRefund } from "../_shared/refunds.ts";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { quotePurchase, routeCost, transactionService } from "../_shared/pricing.ts";
import * as cash from "../_shared/providers/cashsub.ts";
import * as ds from "../_shared/providers/datastation.ts";
import * as legit from "../_shared/providers/legitdataway.ts";
const adapters:any={cashsub:cash,datastation:ds,legitdataway:legit};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"}});
const sha256=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");
Deno.serve(async(req)=>{
 const started=Date.now(),url=new URL(req.url),endpoint=url.pathname.replace(/^\/(?:functions\/v1\/)?datasub-api/,"")||"/";
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-ihlink-api-key","access-control-allow-methods":"GET,POST,OPTIONS"}});
 const apiKey=req.headers.get("x-ihlink-api-key")?.trim();if(!apiKey)return json({error:"missing_api_key",message:"Send your API key in x-ihlink-api-key."},401);
 const client=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
 const hash=await sha256(apiKey);const{data:credential}=await client.from("datasub_api_credentials").select("id,user_id,mode,status,expires_at").eq("key_hash",hash).eq("status","active").maybeSingle();if(!credential||(credential.expires_at&&Date.parse(credential.expires_at)<=Date.now()))return json({error:"invalid_api_key",message:"The API key is invalid or revoked."},401);
 const[{data:owner},{data:access},{data:reseller}]=await Promise.all([client.from("profiles").select("status").eq("id",credential.user_id).maybeSingle(),client.from("customer_service_access").select("status").eq("user_id",credential.user_id).eq("product","datasub").maybeSingle(),client.from("datasub_reseller_accounts").select("status,api_access_approved").eq("user_id",credential.user_id).maybeSingle()]);
 if(owner?.status!=="active"||access?.status!=="active"||reseller?.status!=="active"||reseller?.api_access_approved!==true)return json({error:"api_access_inactive",message:"DataSub API access is not active for this account."},403);
 const {data:withinLimit,error:limitError}=await client.rpc("consume_datasub_api_request",{p_user_id:credential.user_id});
 if(limitError||!withinLimit)return json({error:"rate_limit",message:"Please retry after the next minute."},429);
 let status=200,response:any;
 try{
  if(req.method==="GET"&&endpoint==="/health")response={status:"ok",mode:credential.mode,service:"IHLink DataSub API"};
  else if(req.method==="GET"&&endpoint==="/wallet"){
   const {data,error}=await client.from("datasub_wallets").select("balance").eq("user_id",credential.user_id).maybeSingle();if(error)throw error;response={data:{balance:Number(data?.balance||0),currency:"NGN"}};
  }else if(req.method==="GET"&&endpoint==="/transactions"){
   const reference=url.searchParams.get("reference");if(!reference||!/^[-A-Za-z0-9_:]{8,100}$/.test(reference)){status=400;response={error:"invalid_request",message:"reference is required."};}else{const {data,error}=await client.from("datasub_transactions").select("reference,status,amount,recipient,metadata,routing_state,created_at").eq("user_id",credential.user_id).or("reference.eq.API-"+(await sha256(credential.user_id+":"+reference)).slice(0,32)+",reference.eq."+reference).contains("metadata",{source:"api"}).maybeSingle();if(error)throw error;if(!data){status=404;response={error:"not_found",message:"Transaction not found."};}else response={data:{reference:data.metadata?.api_reference||data.reference,status:data.status==="success"?"successful":data.status,amount:Number(data.amount),recipient:data.recipient,product_code:data.metadata?.product_code,currency:"NGN",refund_status:data.routing_state==="REFUNDED"?"refunded":null,created_at:data.created_at}};}
  }else if(req.method==="GET"&&endpoint==="/quote"){
   const {data:p}=await client.from("datasub_catalog_offerings").select("*").eq("ihlink_plan_id",String(url.searchParams.get("product_code")||"").toUpperCase()).eq("customer_enabled",true).single();
   if(!p)throw new Error("Product unavailable");
   const quote=quotePurchase(String(p.service_type),"api_user",p,url.searchParams.get("amount"));
   response={data:{product_code:p.ihlink_plan_id,service_amount:quote.serviceAmount,fee:quote.fee,amount:quote.charge,currency:"NGN"}};
  }else if(req.method==="GET"&&endpoint==="/products"){
   const service=url.searchParams.get("service")?.toUpperCase();let q=client.from("datasub_customer_catalogue").select("ihlink_plan_id,service_type,network,plan_type,name,validity,api_price").order("service_type").order("network").order("api_price");if(service)q=q.eq("service_type",service);const{data,error}=await q;if(error)throw error;response={data:(data||[]).map((x:any)=>({plan_id:x.ihlink_plan_id,service:x.service_type,network:x.network,type:x.plan_type,name:x.name,validity:x.validity,price:Number(x.api_price)}))};
  }else if(req.method==="POST"&&endpoint==="/purchase"){
   const body=await req.json().catch(()=>null) as any;if(!body?.product_code||!body?.recipient||!body?.reference||!/^[-A-Za-z0-9_:]{8,100}$/.test(String(body.reference))||String(body.recipient).length>100){status=400;response={error:"invalid_request",message:"product_code, recipient and reference are required."};}
   else if(credential.mode==="sandbox")response={data:{reference:body.reference,status:"simulated",product_code:body.product_code,recipient:body.recipient},mode:"sandbox"};
   else{
    const merchantReference=String(body.reference).trim(),internalReference="API-"+(await sha256(credential.user_id+":"+merchantReference)).slice(0,32);
    const{data:existing}=await client.from("datasub_transactions").select("reference,status,amount,recipient,metadata,routing_state").eq("user_id",credential.user_id).or("reference.eq."+internalReference+",reference.eq."+merchantReference).maybeSingle();if(existing){if(existing.metadata?.source!=="api"||existing.metadata?.product_code!==String(body.product_code).trim().toUpperCase()||existing.recipient!==String(body.recipient).trim()||(body.amount!==undefined&&Number(existing.metadata?.service_amount)!==Number(body.amount))){status=409;response={error:"reference_conflict",message:"Use a new reference for a different purchase."};}else response={data:{reference:existing.metadata?.api_reference||existing.reference,status:existing.status==="success"?"successful":existing.status,amount:Number(existing.amount),product_code:existing.metadata?.product_code,refund_status:existing.routing_state==="REFUNDED"?"refunded":null},idempotent:true};}
    else{
     const{data:p}=await client.from("datasub_catalog_offerings").select("*").eq("ihlink_plan_id",String(body.product_code).trim().toUpperCase()).eq("customer_enabled",true).single();if(!p)throw new Error("Product unavailable");
     const service=String(p.service_type).toUpperCase();
     if(["DATA","AIRTIME"].includes(service)&&!/^0[789]\d{9}$/.test(String(body.recipient).trim()))throw new Error("Enter an 11-digit Nigerian phone number.");
     if(service==="ELECTRICITY"&&!["PREPAID","POSTPAID"].includes(String(body.meter_type||"").toUpperCase()))throw new Error("meter_type must be PREPAID or POSTPAID.");
     if(service==="EXAM"&&body.quantity!==undefined&&Number(body.quantity)!==1)throw new Error("Purchase one exam PIN per transaction");
     const quote=quotePurchase(service,"api_user",p,body.amount);
     const {charge:sell,serviceAmount,fee,dynamic:amountBased}=quote;
     if((amountBased&&body.expected_charge===undefined)||(body.expected_charge!==undefined&&Number(body.expected_charge)!==sell))throw new Error("The price changed. Refresh the quote before paying.");
     const{data:rr}=await client.from("datasub_catalog_routes").select("*,upstream:datasub_upstream_catalog!inner(*,provider:datasub_providers!inner(*))").eq("offering_id",p.id).eq("route_enabled",true);
     const maps=(rr||[]).map((r:any)=>{const u=Array.isArray(r.upstream)?r.upstream[0]:r.upstream;return{...r,provider_id:u.provider_id,external_plan_id:u.external_plan_id,provider_cost:u.provider_cost,active:u.active,raw_metadata:u.raw_metadata,provider:Array.isArray(u.provider)?u.provider[0]:u.provider}});
     const ids=maps.map((m:any)=>m.provider_id),{data:hs}=ids.length?await client.from("datasub_provider_health").select("*").in("provider_id",ids):{data:[]};const hm=new Map((hs||[]).map((h:any)=>[h.provider_id,h]));
  const{data:availability,error:availabilityError}=await client.from("datasub_network_availability").select("provider_id,available").eq("service_type",service).eq("network",String(p.network||"").toUpperCase());
  if(availabilityError)throw new Error("Services could not be checked. Please try again.");
  const blockedProviders=new Set((availability||[]).filter((a:any)=>!a.available).map((a:any)=>a.provider_id));
     const eligible=maps.map((m:any)=>({...m,provider_cost:routeCost(serviceAmount,amountBased,m),health:hm.get(m.provider_id)})).filter((m:any)=>!blockedProviders.has(m.provider_id)&&m.active===true&&m.provider?.is_active&&["HEALTHY","DEGRADED"].includes(m.health?.state||m.provider.state)&&Number(m.provider_cost)<=sell).sort((a:any,b:any)=>Number(a.provider_cost)-Number(b.provider_cost)||Number(b.health?.success_rate_15m||0)-Number(a.health?.success_rate_15m||0)||Number(a.health?.average_latency_ms||999999)-Number(b.health?.average_latency_ms||999999));if(!eligible.length)throw new Error("This service is temporarily unavailable. Please try again later.");
     const reference=merchantReference;const{data:tx,error:te}=await client.from("datasub_transactions").insert({user_id:credential.user_id,reference:internalReference,service_type:transactionService(service),provider:"routing",recipient:String(body.recipient).trim(),amount:sell,product_id:null,catalog_offering_id:p.id,selling_price:sell,status:"pending",routing_state:"ROUTING",metadata:{service_amount:serviceAmount,service_fee:fee,cost_basis:amountBased?"face_value_or_configured_provider_rate":"catalogue",source:"api",api_reference:merchantReference,credential_id:credential.id,product_code:p.ihlink_plan_id}}).select().single();if(te)throw te;
     const{data:reserved}=await client.rpc("reserve_datasub_wallet",{p_user:credential.user_id,p_transaction:tx.id,p_amount:sell,p_reference:`RESERVE:${internalReference}`});if(!reserved){await client.from("datasub_transactions").update({status:"failed",routing_state:"FAILED"}).eq("id",tx.id);throw new Error("Insufficient wallet balance")}
     let final:any=null;for(let i=0;i<eligible.length;i++){const m:any=eligible[i],adapter=adapters[m.provider.code];if(!adapter)continue;const requestKey=`${internalReference}:${m.provider.code}`;const result=await adapter.purchase({service:String(p.service_type).toUpperCase(),network:String(p.network||""),recipient:body.recipient,amount:serviceAmount,meter_type:String(body.meter_type||"").toUpperCase(),quantity:service==="EXAM"?1:body.quantity,ported:body.ported},m,requestKey);const safeRaw=JSON.parse(JSON.stringify(result.raw||{},(k,v)=>/token|authorization|password|secret|key/i.test(k)?"[REDACTED]":v));await client.from("datasub_provider_attempts").insert({transaction_id:tx.id,provider_id:m.provider_id,request_key:requestKey,provider_reference:result.reference,provider_cost:m.provider_cost,response_status:result.state,latency_ms:result.latency,safe_response:safeRaw,is_ambiguous:result.state==="UNKNOWN"});if(result.state==="SUCCESS"){await client.from("datasub_transactions").update({provider:m.provider.code,provider_reference:result.reference,provider_cost:m.provider_cost,status:"success",routing_state:"SETTLED"}).eq("id",tx.id);final={reference,status:"successful",product_code:p.ihlink_plan_id,amount:sell,service_amount:serviceAmount,fee};break}if(result.state==="UNKNOWN"){await client.from("datasub_transactions").update({provider:m.provider.code,provider_reference:result.reference,provider_cost:m.provider_cost,routing_state:"RECONCILING"}).eq("id",tx.id);final={reference,status:"pending",product_code:p.ihlink_plan_id,amount:sell,service_amount:serviceAmount,fee};break}}
     if(!final){const refunded=await finalizeRefund(client,tx);final={reference,status:refunded?"failed":"pending",product_code:p.ihlink_plan_id,amount:sell,service_amount:serviceAmount,fee,message:refunded?"The purchase failed and your wallet has been refunded.":"Your wallet refund is being completed."};}
     status=final.status==="successful"?201:final.status==="failed"?502:202;response={data:final};
    }}
  }else{status=404;response={error:"not_found",message:"Use GET /health, /products, /quote, /wallet, /transactions or POST /purchase."};}
 }catch(error){status=400;const message=error instanceof Error?error.message:"Request failed";response={error:"request_failed",message:/insufficient/i.test(message)?"Insufficient wallet balance.":/duplicate/i.test(message)?"The transaction reference already exists.":/Product unavailable|temporarily unavailable|price changed|Nigerian phone|meter_type|Purchase one exam|amount|quantity/i.test(message)?message:"Your request could not be completed. Please try again."};}
 await Promise.all([client.from("datasub_api_usage").insert({credential_id:credential.id,user_id:credential.user_id,endpoint,method:req.method,status_code:status,response_ms:Date.now()-started,request_units:1}),client.from("datasub_api_credentials").update({last_used_at:new Date().toISOString()}).eq("id",credential.id)]);
 return json(response,status);
});