import { verifiedReconciliation } from "./reconciliation.ts";
export type ProviderResult={state:"SUCCESS"|"FAILED"|"UNKNOWN";reference?:string;raw:Record<string,unknown>;latency:number};
const base=()=>Deno.env.get("CASHSUB_API_BASE_URL")||"https://api.cashsub.ng/api";
const token=()=>(Deno.env.get("CASHSUB_API_TOKEN")||"").trim();
const network:Record<string,number>={MTN:1,GLO:2,"9MOBILE":3,T2:3,AIRTEL:4};
function classify(raw:any,httpOk:boolean):"SUCCESS"|"FAILED"|"UNKNOWN"{if(!httpOk){const status=String(raw?.status??raw?.Status??"").toLowerCase();const unavailable=/^(?:MTN|AIRTEL|GLO|9MOBILE|T2) (?:GIFTING|SME|CORPORATE GIFTING) is currently unavailable$/i.test(String(raw?.message??""));const before=Number(raw?.balance_before),after=Number(raw?.balance_after);if(status==="fail"&&unavailable&&raw?.balance_before!=null&&raw?.balance_after!=null&&Number.isFinite(before)&&before===after&&raw?.api_response===null&&!refOf(raw))return "FAILED";return "UNKNOWN";}const s=String(raw?.status??raw?.Status??raw?.transaction_status??"").trim().toLowerCase();if(httpOk&&["success","successful","completed","complete","delivered"].includes(s))return "SUCCESS";if(["fail","failed","failure","error","rejected","cancelled","canceled"].includes(s))return "FAILED";return "UNKNOWN"}
function refOf(raw:any){const v=raw?.reference??raw?.ident??raw?.id??raw?.transaction_id??raw?.request_id;return v==null||String(v)===""?undefined:String(v)}
async function request(root:string,path:string,init:RequestInit={}):Promise<ProviderResult>{const started=Date.now();if(!token())return {state:"UNKNOWN",raw:{configuration:"CASHSUB_API_TOKEN required"},latency:0};try{const r=await fetch(root.replace(/\/$/,"")+"/"+path.replace(/^\//,""),{...init,headers:{Authorization:`Token ${token()}`,"Content-Type":"application/json",Accept:"application/json",...(init.headers||{})}});const parsed=await r.json().catch(()=>({}));const raw={...(parsed&&typeof parsed==="object"?parsed:{}),_http_status:r.status,_endpoint_origin:root};return {state:classify(raw,r.ok),reference:refOf(raw),raw,latency:Date.now()-started}}catch(e){return {state:"UNKNOWN",raw:{error:String(e),_endpoint_origin:root},latency:Date.now()-started}}}
const call=(path:string,init:RequestInit={})=>request(base(),path,init);
export async function health(){const roots=[base(),"https://api.cashsub.ng/api"].filter((v,i,a)=>a.indexOf(v)===i);let last:any;for(const root of roots){const r=await request(root,"/user/");const raw:any=r.raw||{};if(raw._http_status===200&&raw.user&&typeof raw.user==="object")return {...r,state:"SUCCESS" as const};last=r;if(raw._http_status!==404)break}return last||{state:"UNKNOWN",raw:{configuration:"CashSub health endpoint unavailable"},latency:0}}
export async function catalogue(service?:string,networkName?:string){const q=new URLSearchParams();if(service)q.set("service",service);if(networkName)q.set("network",networkName);return call("/plans/?"+q)}
export async function purchase(input:any,mapping:any,key:string){const svc=String(input.service||"DATA").toUpperCase(),n=network[String(input.network||"").toUpperCase()];let path="/data/",body:any={network:n,mobile_number:input.recipient,plan:Number(mapping.external_plan_id),Ported_number:!!input.ported};if(svc==="AIRTIME"){path="/topup/";body={network:n,amount:input.amount,mobile_number:input.recipient,Ported_number:!!input.ported,airtime_type:"VTU"}}else if(svc==="CABLE"){path="/cablesub/";body={cablename:input.network,cableplan:mapping.external_plan_id,smart_card_number:input.recipient}}else if(svc==="ELECTRICITY"){path="/billpayment/";body={disco_name:input.network,amount:input.amount,meter_number:input.recipient,MeterType:input.meter_type}}else if(svc==="EXAM"){path="/epin/";body={exam_name:input.network,quantity:input.quantity||1}}if((svc==="DATA"||svc==="AIRTIME")&&!n)return {state:"FAILED",raw:{validation:"Unsupported CashSub network"},latency:0};return call(path,{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify(body)})}
export async function reconcile(service:string,ref:string){const paths:Record<string,string>={DATA:"data",AIRTIME:"topup",CABLE:"cablesub",ELECTRICITY:"billpayment",EXAM:"epin",SMILE:"smile",ALPHA:"alpha",KIRANI:"kirani"};const path=paths[String(service||"").toUpperCase()];return path?verifiedReconciliation(await call(`/${path}/${encodeURIComponent(ref)}`)):Promise.resolve({state:"UNKNOWN",raw:{configuration:`No verified CashSub reconciliation path for ${service}`},latency:0} as ProviderResult)}
