export type ProviderResult={state:"SUCCESS"|"FAILED"|"UNKNOWN";reference?:string;raw:Record<string,unknown>;latency:number};
const base=()=>Deno.env.get("LEGITDATAWAY_API_BASE_URL")||"https://legitdataway.com/api";
const username=()=>(Deno.env.get("LEGITDATAWAY_USERNAME")||"").trim();
const password=()=>Deno.env.get("LEGITDATAWAY_PASSWORD")||"";
const network:Record<string,number>={MTN:1,AIRTEL:2,GLO:3,"9MOBILE":4,T2:4};
const cable:Record<string,number>={GOTV:1,DSTV:2,STARTIME:3,STARTIMES:3};
const disco:Record<string,number>={"IKEJA ELECTRIC":1,IKEDC:1,"EKO ELECTRIC":2,EKEDC:2,"KANO ELECTRIC":3,KEDCO:3,"PORT HARCOURT ELECTRIC":4,PHEDC:4,"JOS ELECTRIC":5,JEDC:5,"IBADAN ELECTRIC":6,IBEDC:6,"KADUNA ELECTRIC":7,KAEDCO:7,"ABUJA ELECTRIC":8,AEDC:8,"YOLA ELECTRIC":9,YEDC:9,"BENIN ELECTRIC":10,BEDC:10};
const exam:Record<string,number>={WAEC:1,NECO:2,NABTEB:3};
function url(path:string){return base().replace(/\/$/,"")+"/"+path.replace(/^\//,"")}
function classify(raw:any,ok:boolean):"SUCCESS"|"FAILED"|"UNKNOWN"{const s=String(raw?.status??raw?.Status??"").toLowerCase();if(ok&&["success","successful","completed"].includes(s))return "SUCCESS";if(["fail","failed","failure","error"].includes(s))return "FAILED";return "UNKNOWN"}
function ref(raw:any){const v=raw?.ident??raw?.id??raw?.request_id??raw?.["request-id"]??raw?.reference;return v==null||String(v)===""?undefined:String(v)}
async function authenticate(){const started=Date.now();if(!username()||!password())return {ok:false,token:"",raw:{configuration:"LEGITDATAWAY_USERNAME and LEGITDATAWAY_PASSWORD required"},latency:0};try{const basic=btoa(username()+":"+password());const r=await fetch(url("/user"),{method:"POST",headers:{Authorization:"Basic "+basic,"Content-Type":"application/json",Accept:"application/json"}});const parsed=await r.json().catch(()=>({}));const raw={...(parsed&&typeof parsed==="object"?parsed:{}),_http_status:r.status};const token=String((raw as any).AccessToken??(raw as any).access_token??"").trim();return {ok:r.ok&&String((raw as any).status||"").toLowerCase()==="success"&&!!token,token,raw,latency:Date.now()-started}}catch(e){return {ok:false,token:"",raw:{error:String(e)},latency:Date.now()-started}}}
async function call(path:string,init:RequestInit={}){const started=Date.now();const auth=await authenticate();if(!auth.ok)return {state:"FAILED" as const,raw:auth.raw,latency:Date.now()-started};try{const r=await fetch(url(path),{...init,headers:{Authorization:"Token "+auth.token,"Content-Type":"application/json",Accept:"application/json",...(init.headers||{})}});const parsed=await r.json().catch(()=>({}));const raw={...(parsed&&typeof parsed==="object"?parsed:{}),_http_status:r.status};return {state:classify(raw,r.ok),reference:ref(raw),raw,latency:Date.now()-started} as ProviderResult}catch(e){return {state:"UNKNOWN",raw:{error:String(e)},latency:Date.now()-started}}}
export async function health(){const a=await authenticate();const raw:any=a.raw||{};const hasBalance=raw.balance!=null||raw.wallet_balance!=null||raw.Account_Balance!=null;return {state:(a.ok&&hasBalance?"SUCCESS":"FAILED") as "SUCCESS"|"FAILED",raw,latency:a.latency}}
export async function purchase(input:any,mapping:any,key:string){const svc=String(input.service||"DATA").toUpperCase();const n=network[String(input.network||"").toUpperCase()];let path="/data/",body:any={network:n,mobile_number:input.recipient,plan:mapping.external_plan_id,Ported_number:!!input.ported,"request-id":key};if(svc==="AIRTIME"){path="/topup/";body={network:n,amount:input.amount,mobile_number:input.recipient,Ported_number:!!input.ported,airtime_type:"VTU","request-id":key}}else if(svc==="CABLE"){path="/cablesub/";body={cablename:cable[String(input.network||"").toUpperCase()]??input.network,cableplan:mapping.external_plan_id,smart_card_number:input.recipient,"request-id":key}}else if(svc==="ELECTRICITY"){path="/billpayment/";body={disco_name:disco[String(input.network||"").toUpperCase()]??input.network,amount:input.amount,meter_number:input.recipient,MeterType:input.meter_type,"request-id":key}}else if(svc==="EXAM"){path="/epin/";body={exam_name:exam[String(input.network||"").toUpperCase()]??input.network,quantity:input.quantity||1,"request-id":key}}if((svc==="DATA"||svc==="AIRTIME")&&!n)return {state:"FAILED",raw:{validation:"Unsupported Legitdataway network"},latency:0} as ProviderResult;return call(path,{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify(body)})}
export async function reconcile(service:string,refId:string){const roots:Record<string,string>={DATA:"/data/",AIRTIME:"/topup/",CABLE:"/cablesub/",ELECTRICITY:"/billpayment/",EXAM:"/epin/"};const root=roots[String(service||"").toUpperCase()];if(!root)return {state:"UNKNOWN",raw:{configuration:"Unsupported Legitdataway reconciliation service"},latency:0} as ProviderResult;return call(root+encodeURIComponent(refId),{method:"GET"})}
