import {Link} from 'react-router-dom';
import {Smartphone,Phone,Zap,Tv,GraduationCap,Grid2X2} from 'lucide-react';
import {useAuth} from '@/context/AuthContext';
import {useDataSubData} from '@/hooks/useDataSubData';
import {naira} from '@/lib/designTokens';
export function NativeAppHome(){
 const {user}=useAuth();const {wallet,error}=useDataSubData();
 const services=[{label:'Buy data',to:'/datasub/buy/data',icon:Smartphone},{label:'Airtime',to:'/datasub/buy/airtime',icon:Phone},{label:'Electricity',to:'/datasub/buy/electricity',icon:Zap},{label:'Cable TV',to:'/datasub/buy/cable',icon:Tv},{label:'Education',to:'/datasub/buy/education',icon:GraduationCap},{label:'All services',to:'/datasub/services',icon:Grid2X2}];
 return <main className="mx-auto max-w-xl space-y-6 p-4"><section className="rounded-3xl bg-emerald-800 p-5 text-white"><h1 className="text-sm font-semibold">Your DataSub account</h1><p className="mt-3 text-3xl font-extrabold">{user?naira(wallet.balance):'Welcome to DataSub'}</p><p className="mt-2 text-sm text-emerald-100">{user?'Available balance':'Data, airtime and bills in one place.'}</p><Link to={user?'/datasub/wallet':'/signin'} className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-white px-5 font-bold text-emerald-800">{user?'Fund wallet':'Sign in'}</Link>{!user&&<Link to="/register" className="ml-4 inline-flex min-h-11 items-center text-sm font-semibold">Create account</Link>}</section>{error&&user&&<p role="status" className="text-sm text-rose-700">{error}</p>}<section><h2 className="mb-3 text-lg font-bold">What would you like to do?</h2><div className="grid grid-cols-3 gap-3">{services.map(({label,to,icon:Icon})=><Link key={to} to={to} className="flex min-h-24 flex-col items-center justify-center gap-3 rounded-2xl border bg-white px-2 text-center text-sm font-semibold"><Icon className="h-6 w-6 text-emerald-700"/>{label}</Link>)}</div></section><Link to="/datasub/services" className="flex min-h-12 items-center justify-center rounded-xl border bg-white font-semibold">Explore services</Link>{user&&<div className="grid grid-cols-2 gap-3"><Link className="rounded-xl border bg-white p-4 text-sm font-semibold" to="/datasub/transactions">Transaction history</Link><Link className="rounded-xl border bg-white p-4 text-sm font-semibold" to="/datasub/dashboard">My dashboard</Link></div>}</main>;
}