import {NativeAccountCards} from '@/components/NativeAccountCards';
import {isNativeApp} from '@/lib/nativeAuth';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Save, Trash2, Palette, Moon, Sun } from 'lucide-react';
import { ModulePage } from '@/components/ModulePage';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { useAccountSections } from './accountShared';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';

type Form={first_name:string;middle_name:string;last_name:string;phone:string;sex:string;newsletter_opt_in:boolean};
const empty:Form={first_name:'',middle_name:'',last_name:'',phone:'',sex:'',newsletter_opt_in:true};
const field='w-full rounded-xl border border-border bg-white px-3 py-3 text-sm outline-none focus:border-royal-500 focus:ring-2 focus:ring-royal-100';

export function ProfilePage(){
 const accountSections=useAccountSections();
 const {user,profile,signOut}=useAuth();
 const [form,setForm]=useState<Form>(empty),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[isError,setIsError]=useState(false),[dataSubPlan,setDataSubPlan]=useState('Standard Access');
 const [appearance,setAppearance]=useState(()=>localStorage.getItem('ihlink-appearance')||'light');
 const [density,setDensity]=useState(()=>localStorage.getItem('ihlink-density')||'comfortable');
 useEffect(()=>{async function load(){if(!supabase||!user)return;const {data}=await supabase.from('profiles').select('first_name,middle_name,last_name,phone,sex,newsletter_opt_in').eq('id',user.id).single();if(data)setForm({first_name:data.first_name||'',middle_name:data.middle_name||'',last_name:data.last_name||'',phone:data.phone||'',sex:data.sex||'',newsletter_opt_in:Boolean(data.newsletter_opt_in)});const {data:access}=await supabase.from('customer_service_access').select('plan_name').eq('user_id',user.id).eq('product','datasub').maybeSingle();if(access?.plan_name)setDataSubPlan(access.plan_name);}void load();},[user]);
 const update=(key:keyof Form,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
 function applyAppearance(value:string){setAppearance(value);localStorage.setItem('ihlink-appearance',value);document.documentElement.dataset.appearance=value;}
 function applyDensity(value:string){setDensity(value);localStorage.setItem('ihlink-density',value);document.documentElement.dataset.density=value;}
 async function save(){if(!supabase||!user)return;setBusy(true);setNotice('');const {error}=await supabase.from('profiles').update({...form,sex:form.sex||null,updated_at:new Date().toISOString()}).eq('id',user.id);setBusy(false);setIsError(Boolean(error));setNotice(error?'Your profile could not be saved. Please try again.':'Your profile information has been saved.');}
 async function requestAccountDeletion(){if(!supabase||!user||!window.confirm('Request permanent deletion of your IHLink account? You can cancel the request before it is processed.'))return;setBusy(true);const {error}=await supabase.from('account_deletion_requests').upsert({user_id:user.id,status:'pending',requested_at:new Date().toISOString()},{onConflict:'user_id,status'});setBusy(false);setIsError(Boolean(error));setNotice(error?'Your deletion request could not be submitted. Please try again.':'Account deletion request submitted. Your account remains accessible until the request is processed.');}
 async function clearPersonalInfo(){if(!supabase||!user||!window.confirm('Delete your optional profile information? Your account and email will remain active.'))return;setBusy(true);const cleared={first_name:'',middle_name:'',last_name:'',phone:'',sex:'',newsletter_opt_in:false};const {error}=await supabase.from('profiles').update({first_name:null,middle_name:null,last_name:null,phone:null,sex:null,newsletter_opt_in:false,updated_at:new Date().toISOString()}).eq('id',user.id);setBusy(false);if(error){setIsError(true);setNotice('Your changes could not be saved. Please try again.');}else{setForm(cleared);setIsError(false);setNotice('Optional profile information deleted. Your account remains active.');}}
 const name=[form.first_name,form.middle_name,form.last_name].filter(Boolean).join(' ')||profile?.email||'IHLink Customer';
 return <ModulePage product="datasub" sections={accountSections} title="Profile & Security" description="View, edit, save or remove your personal profile information." userName={name} userRole="IHLink Customer" primaryAction="Save profile">
  {isNativeApp()&&<NativeAccountCards/>}
  {notice&&<div className={`rounded-xl border p-3 text-sm ${isError?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{notice}</div>}
  <div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><Card><h3 className="text-lg font-bold">Personal information</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">First name<input className={`${field} mt-2`} value={form.first_name} onChange={e=>update('first_name',e.target.value)}/></label><label className="text-sm font-bold">Middle name<input className={`${field} mt-2`} value={form.middle_name} onChange={e=>update('middle_name',e.target.value)}/></label><label className="text-sm font-bold">Surname / last name<input className={`${field} mt-2`} value={form.last_name} onChange={e=>update('last_name',e.target.value)}/></label><label className="text-sm font-bold">Phone number<input className={`${field} mt-2`} value={form.phone} onChange={e=>update('phone',e.target.value)}/></label><label className="text-sm font-bold">Sex<select className={`${field} mt-2`} value={form.sex} onChange={e=>update('sex',e.target.value)}><option value="">Choose an option</option><option value="male">Male</option><option value="female">Female</option><option value="prefer_not_to_say">Prefer not to say</option></select></label><label className="text-sm font-bold">Email address<input className={`${field} mt-2 bg-slate-50`} value={profile?.email||''} disabled/><span className="mt-1 block text-xs font-normal text-muted">Email changes require account verification.</span></label></div><label className="mt-5 flex items-start gap-3 rounded-xl border p-4"><input type="checkbox" checked={form.newsletter_opt_in} onChange={e=>update('newsletter_opt_in',e.target.checked)} className="mt-1 h-4 w-4 accent-royal-600"/><span><b className="block text-sm">IHLink updates and newsletter</b><span className="text-xs text-muted">Receive service announcements, promotions and useful product updates by email.</span></span></label><div className="mt-5 flex flex-wrap gap-3"><Button disabled={busy} leftIcon={<Save className="h-4 w-4"/>} onClick={()=>void save()}>{busy?'Saving…':'Save profile'}</Button><Button disabled={busy} variant="danger" leftIcon={<Trash2 className="h-4 w-4"/>} onClick={()=>void clearPersonalInfo()}>Delete profile information</Button></div></Card>
  <Card><h3 className="text-lg font-bold">DataSub access</h3><div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">Current plan</p><p className="mt-1 text-xl font-extrabold text-emerald-900">{dataSubPlan}</p><p className="mt-1 text-xs text-emerald-700">Your current DataSub plan.</p></div><Link to="/datasub/upgrade" className="mt-4 block"><Button fullWidth>View reseller & API upgrades</Button></Link><h3 className="mt-7 text-lg font-bold">Account security</h3><div className="mt-5 rounded-xl bg-emerald-50 p-4"><p className="font-bold text-emerald-900">Authenticated account</p><p className="mt-1 text-xs text-emerald-700">Manage your password and app access.</p></div><Link to="/reset-password" className="mt-4 block"><Button fullWidth variant="secondary">Change password</Button></Link><Button fullWidth variant="secondary" className="mt-3" onClick={()=>void signOut()}>Sign out</Button></Card></div>
 <Card><div className="flex items-center gap-2"><Palette className="h-5 w-5 text-royal-600"/><h3 className="text-lg font-bold">Appearance & preferences</h3></div><p className="mt-1 text-sm text-muted">These preferences follow the IHLink interface across the platforms you open on this browser.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><div><p className="text-sm font-bold">Theme</p><div className="mt-2 flex flex-wrap gap-2"><Button variant={appearance==='light'?'primary':'secondary'} leftIcon={<Sun className="h-4 w-4"/>} onClick={()=>applyAppearance('light')}>Light</Button><Button variant={appearance==='dark'?'primary':'secondary'} leftIcon={<Moon className="h-4 w-4"/>} onClick={()=>applyAppearance('dark')}>Dark</Button><Button variant={appearance==='system'?'primary':'secondary'} onClick={()=>applyAppearance('system')}>System</Button></div></div><label className="text-sm font-bold">Interface spacing<select className={`${field} mt-2`} value={density} onChange={e=>applyDensity(e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label></div></Card><Card className="border-rose-200"><h3 className="text-lg font-bold text-rose-700">Account controls</h3><p className="mt-1 text-sm text-muted">Remove optional profile information or request permanent account deletion. </p><div className="mt-4 flex flex-wrap gap-3"><Button disabled={busy} variant="danger" leftIcon={<Trash2 className="h-4 w-4"/>} onClick={()=>void requestAccountDeletion()}>Request account deletion</Button></div></Card></ModulePage>;
}
