-- DataSub provider market pricing control and audit
create table if not exists public.datasub_pricing_audit (id uuid primary key default gen_random_uuid(),offering_id uuid references public.datasub_catalog_offerings(id) on delete set null,provider_id uuid references public.datasub_providers(id) on delete set null,action text not null,field_name text,old_value jsonb,new_value jsonb,reason text,changed_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
alter table public.datasub_pricing_audit enable row level security;
grant select on public.datasub_pricing_audit to authenticated,service_role;
revoke insert,update,delete on public.datasub_pricing_audit from anon,authenticated;
drop policy if exists "datasub admins read pricing audit" on public.datasub_pricing_audit;
create policy "datasub admins read pricing audit" on public.datasub_pricing_audit for select to authenticated using (private.has_product_access('datasub','view'));

create or replace function public.datasub_admin_update_market_price(p_offering uuid,p_smart numeric,p_reseller numeric,p_api numeric,p_top numeric,p_reason text default 'manual market update') returns void language plpgsql security definer set search_path='' as $$ declare o public.datasub_catalog_offerings; uid uuid:=auth.uid(); begin if uid is null or not private.has_product_access('datasub','edit') then raise exception 'Not authorized'; end if; select * into o from public.datasub_catalog_offerings where id=p_offering for update; if o.id is null then raise exception 'Offering not found'; end if; if least(p_smart,p_reseller,p_api,p_top)<o.base_provider_cost then raise exception 'Selling price cannot be below current base provider cost'; end if; update public.datasub_catalog_offerings set smart_earner_price=p_smart,reseller_price=p_reseller,api_price=p_api,top_seller_price=p_top,updated_at=now() where id=o.id; insert into public.datasub_pricing_audit(offering_id,action,field_name,old_value,new_value,reason,changed_by) values(o.id,'PRICE_UPDATE','selling_prices',jsonb_build_object('smart',o.smart_earner_price,'reseller',o.reseller_price,'api',o.api_price,'top',o.top_seller_price),jsonb_build_object('smart',p_smart,'reseller',p_reseller,'api',p_api,'top',p_top),nullif(trim(p_reason),''),uid); end$$;
revoke all on function public.datasub_admin_update_market_price(uuid,numeric,numeric,numeric,numeric,text) from public,anon; grant execute on function public.datasub_admin_update_market_price(uuid,numeric,numeric,numeric,numeric,text) to authenticated,service_role;

create or replace function public.datasub_admin_bulk_market_adjust(p_service text default null,p_network text default null,p_plan_type text default null,p_tier text default 'smart_earner',p_mode text default 'percent',p_value numeric default 0,p_reason text default 'market adjustment') returns integer language plpgsql security definer set search_path='' as $$ declare r record; n int:=0; oldp numeric; newp numeric; uid uuid:=auth.uid(); begin if uid is null or not private.has_product_access('datasub','edit') then raise exception 'Not authorized'; end if; if p_tier not in ('smart_earner','reseller','api','top_seller') then raise exception 'Invalid tier'; end if; if p_mode not in ('percent','fixed') then raise exception 'Invalid adjustment mode'; end if; for r in select * from public.datasub_catalog_offerings o where (p_service is null or o.service_type=p_service) and (p_network is null or o.network=p_network) and (p_plan_type is null or o.plan_type=p_plan_type) loop oldp:=case p_tier when 'smart_earner' then r.smart_earner_price when 'reseller' then r.reseller_price when 'api' then r.api_price else r.top_seller_price end; newp:=case when p_mode='percent' then round(oldp*(1+p_value/100.0),2) else oldp+p_value end; newp:=greatest(newp,r.base_provider_cost); update public.datasub_catalog_offerings set smart_earner_price=case when p_tier='smart_earner' then newp else smart_earner_price end,reseller_price=case when p_tier='reseller' then newp else reseller_price end,api_price=case when p_tier='api' then newp else api_price end,top_seller_price=case when p_tier='top_seller' then newp else top_seller_price end,updated_at=now() where id=r.id; insert into public.datasub_pricing_audit(offering_id,action,field_name,old_value,new_value,reason,changed_by) values(r.id,'BULK_MARKET_ADJUST',p_tier,to_jsonb(oldp),to_jsonb(newp),nullif(trim(p_reason),''),uid); n:=n+1; end loop; return n; end$$;
revoke all on function public.datasub_admin_bulk_market_adjust(text,text,text,text,text,numeric,text) from public,anon; grant execute on function public.datasub_admin_bulk_market_adjust(text,text,text,text,text,numeric,text) to authenticated,service_role;

create or replace function public.datasub_admin_update_upstream_route(p_upstream uuid,p_cost numeric,p_active boolean,p_reason text default 'provider market update') returns void language plpgsql security definer set search_path='' as $$ declare u public.datasub_upstream_catalog; uid uuid:=auth.uid(); begin if uid is null or not private.has_product_access('datasub','edit') then raise exception 'Not authorized'; end if; if p_cost<0 then raise exception 'Provider cost cannot be negative'; end if; select * into u from public.datasub_upstream_catalog where id=p_upstream for update; if u.id is null then raise exception 'Upstream route not found'; end if; update public.datasub_upstream_catalog set provider_cost=p_cost,active=p_active,last_synced_at=now() where id=u.id; insert into public.datasub_pricing_audit(provider_id,action,field_name,old_value,new_value,reason,changed_by) values(u.provider_id,'UPSTREAM_ROUTE_UPDATE','provider_cost_active',jsonb_build_object('cost',u.provider_cost,'active',u.active),jsonb_build_object('cost',p_cost,'active',p_active),nullif(trim(p_reason),''),uid); update public.datasub_catalog_offerings o set base_provider_cost=coalesce((select min(u2.provider_cost) from public.datasub_catalog_routes r join public.datasub_upstream_catalog u2 on u2.id=r.upstream_catalog_id where r.offering_id=o.id and r.route_enabled and u2.active),o.base_provider_cost),updated_at=now() where exists(select 1 from public.datasub_catalog_routes r where r.offering_id=o.id and r.upstream_catalog_id=u.id); end$$;
revoke all on function public.datasub_admin_update_upstream_route(uuid,numeric,boolean,text) from public,anon; grant execute on function public.datasub_admin_update_upstream_route(uuid,numeric,boolean,text) to authenticated,service_role;

create or replace function public.datasub_admin_set_provider_state(p_provider uuid,p_active boolean,p_priority integer,p_reason text default 'admin provider control') returns void language plpgsql security definer set search_path='' as $$ declare p public.datasub_providers; a public.datasub_provider_activation_checks; uid uuid:=auth.uid(); begin if uid is null or not private.has_product_access('datasub','edit') then raise exception 'Not authorized'; end if; select * into p from public.datasub_providers where id=p_provider for update; if p.id is null then raise exception 'Provider not found'; end if; if p_active then select * into a from public.datasub_provider_activation_checks where provider_id=p.id; if not coalesce(a.credentials_configured,false) or not coalesce(a.health_verified,false) or not coalesce(a.balance_verified,false) or not coalesce(a.catalogue_verified,false) or not coalesce(a.routing_verified,false) then raise exception 'Provider activation checks are incomplete'; end if; end if; update public.datasub_providers set is_active=p_active,priority=greatest(1,p_priority),state=case when p_active and state='DISABLED' then 'HEALTHY' when not p_active then 'DISABLED' else state end,updated_at=now() where id=p.id; insert into public.datasub_pricing_audit(provider_id,action,field_name,old_value,new_value,reason,changed_by) values(p.id,'PROVIDER_STATE','active_priority',jsonb_build_object('active',p.is_active,'priority',p.priority),jsonb_build_object('active',p_active,'priority',greatest(1,p_priority)),nullif(trim(p_reason),''),uid); end$$;
revoke all on function public.datasub_admin_set_provider_state(uuid,boolean,integer,text) from public,anon; grant execute on function public.datasub_admin_set_provider_state(uuid,boolean,integer,text) to authenticated,service_role;