import {useCallback,useEffect,useState} from 'react';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
type Hook={id:string;url:string;active:boolean};
type Delivery={id:string;event_type:string;status:string;attempts:number;created_at:string};
export function ApiWebhookSettings(){
 const {user}=useAuth();const [hook,setHook]=useState<Hook|null>(null),[url,setUrl]=useState(''),[secret,setSecret]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[deliveries,setDeliveries]=useState<Delivery[]>([]);
 const load=useCallback(async()=>{if(!supabase||!user)return;const [h,d]=await Promise.all([supabase.from('datasub_api_webhooks').select('id,url,active').eq('user_id',user.id).order('created_at').limit(1).maybeSingle(),supabase.from('datasub_webhook_deliveries').select('id,event_type,status,attempts,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(20)]);if(h.error||d.error){setNotice('Your callback settings could not be loaded. Please refresh.');return;}setHook(h.data);setUrl(h.data?.url||'');setDeliveries(d.data||[]);},[user]);
 useEffect(()=>{setSecret('');void load();},[load]);
 async function save(){if(!supabase)return;setBusy(true);setSecret('');setNotice('');const {data,error}=await supabase.rpc('configure_datasub_api_webhook',{p_url:url.trim()});if(error)setNotice('Enter a public HTTPS callback URL and check that your API access is active.');else{setSecret(data.secret);setNotice('Callback saved. Copy the new signing secret now; the previous secret no longer applies.');await load();}setBusy(false);}
 async function disable(){if(!supabase||!hook)return;setBusy(true);const {error}=await supabase.rpc('disable_datasub_api_webhook',{p_webhook_id:hook.id});setSecret('');setNotice(error?'The callback could not be disabled. Please try again.':'Callback disabled. Pending deliveries have been cancelled.');if(!error)await load();setBusy(false);}
 async function copy(){try{await navigator.clipboard.writeText(secret);setNotice('Signing secret copied. Store it on your server.');}catch{setNotice('Copy the signing secret from the field below.');}}
 return <Card className="mt-6"><h3 className="text-lg font-bold">Purchase callbacks</h3><p className="mt-2 text-sm text-muted">Receive signed success and failure events on your website. Your server must verify the signature and acknowledge each event with a successful HTTP response.</p><label className="mt-4 block text-sm font-semibold">HTTPS callback URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-site.example/ihlink/callback" className="mt-2 w-full rounded-xl border p-3"/></label><div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy||!url.trim()} onClick={()=>void save()}>{hook?'Save and rotate secret':'Save callback'}</Button>{hook?.active&&<Button variant="secondary" disabled={busy} onClick={()=>void disable()}>Disable callback</Button>}<Button variant="secondary" disabled={busy} onClick={()=>void load()}>Refresh deliveries</Button></div>{notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}{secret&&<div className="mt-4 rounded-xl bg-slate-950 p-4 text-white"><code className="block break-all text-sm">{secret}</code><Button variant="secondary" className="mt-3" onClick={()=>void copy()}>Copy signing secret</Button><p className="mt-2 text-xs">This secret is shown once. Saving again replaces it.</p></div>}<p className="mt-4 text-sm font-semibold">Delivery history {hook?hook.active?'· Active':'· Disabled':''}</p><div className="mt-2 space-y-2">{deliveries.map(d=><div key={d.id} className="flex flex-wrap justify-between gap-2 rounded-lg border p-3 text-xs"><span>{d.event_type}</span><span>{d.status} · {d.attempts} attempt{d.attempts===1?'':'s'}</span></div>)}{!deliveries.length&&<p className="text-sm text-muted">No callback deliveries yet.</p>}</div></Card>;
}
