import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRightLeft} from 'lucide-react';
import {DashboardLayout} from '@/components/Sidebar';
import {useDataSubData} from '@/hooks/useDataSubData';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
import {naira} from '@/lib/designTokens';
type Recipient={account_id:string;account_name:string;account_number:string;bank_name:string};
export function DataSubTransfer(){
 const {user}=useAuth();const {wallet,userName,refresh}=useDataSubData();const [account,setAccount]=useState(''),[bank,setBank]=useState('9PSB'),[amount,setAmount]=useState(''),[pin,setPin]=useState(''),[recipient,setRecipient]=useState<Recipient|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[history,setHistory]=useState<{id:string;amount:number;created_at:string;sender_id:string}[]>([]);const [pending,setPending]=useState(false);const request=useRef<string|null>(null);const lookup=useRef(0);
 useEffect(()=>{if(!user)return;try{const saved=JSON.parse(localStorage.getItem('ihlink.datasub.pending-transfer.'+user.id)||'null');if(saved?.request&&saved.recipient?.account_id){request.current=saved.request;setAccount(saved.recipient.account_number);setBank(saved.bank);setAmount(saved.amount);setRecipient(saved.recipient);setPending(true);setNotice('A previous transfer needs confirmation. Retry with these details to check it safely.');}}catch{}},[user?.id]);
 useEffect(()=>{let active=true;if(user&&supabase)void supabase.from('datasub_wallet_transfers').select('id,amount,created_at,sender_id').or(`sender_id.eq.${user.id},recipient_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(30).then(({data})=>{if(active)setHistory(data||[]);});return()=>{active=false;};},[user,notice]);
 function invalidate(){lookup.current++;setRecipient(null);request.current=null;setNotice('');}
 async function find(){if(!supabase||account.length!==10)return;const revision=++lookup.current;setBusy(true);setNotice('');try{const r=await supabase.rpc('datasub_transfer_recipient',{p_account:account,p_bank:bank});if(revision!==lookup.current)return;if(r.error||!r.data){setRecipient(null);setNotice('No active IHLinker account matched. Check the account number and bank.');}else setRecipient(r.data);}catch{setNotice('The account could not be checked. Try again shortly.');}finally{setBusy(false);}}
 async function send(){if(!supabase||!recipient||busy)return;const value=Number(amount);if(!Number.isFinite(value)||value<=0||!/^\d+(?:\.\d{1,2})?$/.test(amount)||pin.length!==4){setNotice('Enter a valid amount and your four-digit purchase PIN.');return;}if(!window.confirm(`Transfer ${naira(value)} to ${recipient.account_name} (${recipient.account_number})?`))return;setBusy(true);setNotice('');request.current||=crypto.randomUUID();if(user)localStorage.setItem('ihlink.datasub.pending-transfer.'+user.id,JSON.stringify({request:request.current,recipient,amount,bank}));setPending(true);try{const r=await supabase.rpc('datasub_transfer_wallet',{p_account_id:recipient.account_id,p_amount:value,p_pin:pin,p_request_id:request.current});if(r.error){setNotice('The transfer could not be confirmed. Retry with the same details to check it safely.');}else if(!r.data?.ok){setNotice(r.data?.message||'The transfer could not be completed.');setPending(false);request.current=null;if(user)localStorage.removeItem('ihlink.datasub.pending-transfer.'+user.id);}else{setNotice(`Transfer successful. Reference: ${r.data.id}`);setPin('');request.current=null;setPending(false);if(user)localStorage.removeItem('ihlink.datasub.pending-transfer.'+user.id);setRecipient(null);setAmount('');await refresh();}}catch{setNotice('Your transfer has not been confirmed. Keep the details unchanged and retry.');}finally{setBusy(false);}}
 return <DashboardLayout product="datasub" sections={[]} userName={userName} userRole="Customer" pageTitle="Send to IHLinker"><section className="app-card"><ArrowRightLeft/><h2 className="mt-3 text-lg font-bold">Transfer between DataSub wallets</h2><p className="app-muted mt-2 text-sm">Use the recipient’s BillStack funding account to find their IHLinker wallet. Money moves between IHLinker wallets; this sends no bank payout.</p><p className="mt-3 font-bold">Available: {naira(wallet.balance)}</p><div className="mt-5 grid gap-4"><label className="text-sm font-semibold">Receiving bank<select disabled={busy||pending} className="mt-2 w-full rounded-xl border p-3" value={bank} onChange={e=>{invalidate();setBank(e.target.value);}}><option value="9PSB">9PSB</option><option value="PALMPAY">PalmPay</option></select></label><label className="text-sm font-semibold">IHLinker funding account number<input disabled={busy||pending} inputMode="numeric" maxLength={10} value={account} onChange={e=>{invalidate();setAccount(e.target.value.replace(/\D/g,'').slice(0,10));}} className="mt-2 w-full rounded-xl border p-3"/></label><button type="button" disabled={busy||pending||account.length!==10} className="app-action" onClick={()=>void find()}>Check recipient</button>{recipient&&<><div className="rounded-xl border p-3"><b>{recipient.account_name}</b><p className="app-muted mt-1 text-sm">{recipient.bank_name} · {recipient.account_number}</p></div><label className="text-sm font-semibold">Amount (₦)<input disabled={busy||pending} inputMode="decimal" value={amount} onChange={e=>{request.current=null;setAmount(e.target.value);}} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Four-digit purchase PIN<input disabled={busy} type="password" inputMode="numeric" autoComplete="off" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} className="mt-2 w-full rounded-xl border p-3"/></label><button type="button" disabled={busy} className="app-action" onClick={()=>void send()}>{busy?'Confirming…':'Confirm transfer'}</button></>}{notice&&<p role="status" className="break-words text-sm">{notice}</p>}<Link to="/datasub/wallet" className="min-h-11 py-3 text-sm font-semibold">Funding accounts & purchase PIN</Link></div></section><section className="app-card mt-4"><h2 className="font-bold">Wallet transfers</h2>{history.map(item=><div key={item.id} className="app-list-row"><div className="min-w-0"><b>{item.sender_id===user?.id?'Sent':'Received'}</b><p className="app-muted mt-1 text-xs">{new Date(item.created_at).toLocaleString('en-NG')}</p><p className="app-muted break-all text-xs">{item.id}</p></div><b className="shrink-0 text-sm">{naira(Number(item.amount))}</b></div>)}{!history.length&&<p className="app-muted py-4 text-sm">No wallet transfers yet.</p>}</section></DashboardLayout>;
}
