import {useEffect,useState} from 'react';
import {Users,Copy,Share2} from 'lucide-react';
import {DashboardLayout} from '@/components/Sidebar';
import {useAuth} from '@/context/AuthContext';
import {useDataSubData} from '@/hooks/useDataSubData';
import {supabase} from '@/lib/supabase';
import {naira} from '@/lib/designTokens';
export function DataSubReferrals(){
 const {user}=useAuth();const {wallet,userName,refresh}=useDataSubData();const [code,setCode]=useState(''),[count,setCount]=useState(0),[terms,setTerms]=useState<{enabled:boolean;reward_amount:number;minimum_purchase:number}|null>(null),[notice,setNotice]=useState(''),[inviter,setInviter]=useState(()=>new URLSearchParams(window.location.search).get('ref')||''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;if(!supabase||!user)return;void Promise.all([supabase.rpc('datasub_referral_code'),supabase.from('datasub_referral_invitees').select('referred_user_id',{count:'exact',head:true}).eq('referrer_user_id',user.id),supabase.from('datasub_referral_program').select('enabled,reward_amount,minimum_purchase').eq('id',true).single()]).then(([c,i,t])=>{if(!active)return;if(c.error||i.error||t.error)setNotice('Referral details could not be loaded. Please try again shortly.');else{setCode(c.data);setCount(i.count||0);setTerms(t.data);}setLoading(false);});return()=>{active=false;};},[user]);
 const link=code?`https://ihlink-datasub.onrender.com/register?ref=${encodeURIComponent(code)}`:'';
 async function copy(){try{await navigator.clipboard.writeText(link);setNotice('Referral link copied.');}catch{setNotice('Copy the referral link shown below.');}}
 async function share(){try{if(navigator.share)await navigator.share({title:'Join IHLink DataSub',text:'Use my invitation to join IHLink DataSub.',url:link});else await copy();}catch{setNotice('Sharing was not completed. You can copy the link instead.');}}
 async function move(){if(!supabase)return;const r=await supabase.rpc('move_datasub_referral_earnings');setNotice(r.error?'Earnings could not be moved. Please try again.':Number(r.data)>0?'Verified earnings moved to your wallet.':'No available referral earnings to move.');await refresh();}
 async function claim(){if(!supabase||!inviter.trim())return;const r=await supabase.rpc('datasub_claim_referral',{p_code:inviter.trim()});setNotice(!r.error&&r.data?'Invitation linked to your account.':'This invitation could not be applied. Verify your email first; invitations apply before your first purchase.');}
 return <DashboardLayout product="datasub" sections={[]} userName={userName} userRole="Customer" pageTitle="Refer & earn"><section className="app-card"><Users className="h-9 w-9"/><h2 className="mt-3 text-xl font-bold">Invite friends to DataSub</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border p-3"><p className="app-muted text-xs">Joined from your invitation</p><b className="mt-2 block text-xl">{loading?'…':count}</b></div><div className="rounded-xl border p-3"><p className="app-muted text-xs">Referral earnings balance</p><b className="mt-2 block text-xl">{naira(wallet.referralBalance||0)}</b></div></div><button type="button" disabled={wallet.referralBalance<=0} className="app-action mt-4" onClick={()=>void move()}>Move earnings to wallet</button><p className="app-muted mt-4 text-sm">{terms?.enabled?`Current programme: ${naira(Number(terms.reward_amount))} after a qualifying purchase of at least ${naira(Number(terms.minimum_purchase))}. Rewards require verification.`:'Referral rewards are not active yet. You can still invite friends; new rewards will appear when IHLink announces the programme.'}</p>{link&&<><label className="mt-4 block text-sm font-semibold">Your invitation link<input readOnly value={link} onFocus={e=>e.target.select()} className="mt-2 w-full rounded-xl border p-3 text-sm"/></label><div className="mt-3 grid grid-cols-2 gap-3"><button type="button" className="app-action" onClick={()=>void copy()}><Copy size={18}/>Copy link</button><button type="button" className="app-action app-action-secondary" onClick={()=>void share()}><Share2 size={18}/>Share</button></div></>}{notice&&<p role="status" className="mt-4 text-sm">{notice}</p>}</section><section className="app-card mt-4"><h2 className="font-bold">How it works</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm"><li>Share your invitation link with a friend.</li><li>They create and verify their IHLink account, then apply your invitation.</li><li>Qualifying, verified rewards appear in your referral earnings.</li></ol></section><section className="app-card mt-4"><h2 className="font-bold">Invited by a friend?</h2><label className="mt-3 block text-sm">Invitation code<input value={inviter} onChange={e=>setInviter(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><button type="button" className="app-action mt-3" onClick={()=>void claim()}>Apply invitation</button></section></DashboardLayout>;
}
