import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/AuthContext';
import { PageShell } from '@/components/PageShell';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { ServiceLogo } from '@/components/ServiceLogo';
import { networks } from '@/lib/datasubServices';
import { naira } from '@/lib/designTokens';
import { Printer, Wifi, Smartphone } from 'lucide-react';

export function DataSubPrintCards(){
 const {user}=useAuth(); const navigate=useNavigate(); const [params]=useSearchParams(); const requestedType=params.get('type'); const [kind,setKind]=useState<'data'|'airtime'>(requestedType==='airtime'?'airtime':'data'),[network,setNetwork]=useState('MTN'),[quantity,setQuantity]=useState(10),[value,setValue]=useState(500),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 async function submit(){if(!user){navigate('/signin',{state:{from:'/datasub/print-cards'}});return;}if(!supabase)return;setSaving(true);const {error}=await supabase.from('datasub_voucher_batches').insert({user_id:user.id,voucher_type:kind,network,denomination:value,quantity,status:'awaiting_provider'});setSaving(false);setNotice(error?error.message:'Batch request saved. Provider-authorized PIN generation will start when that integration is activated.');}
 return <PageShell product="datasub"><div className="mx-auto max-w-[1180px] px-6 py-12">
  <Badge className="mb-3 bg-emerald-50 text-emerald-700">Printable Cards</Badge><h1 className="text-3xl font-extrabold">Print Data & Airtime Cards</h1><p className="mt-2 mb-8 text-sm text-muted">Prepare branded printable voucher batches for reseller operations. PIN/code generation remains disabled until an authorized production provider is connected.</p>
  <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><Card padding="lg"><div className="grid grid-cols-2 gap-3">{([{id:'data',label:'Data Card',icon:Wifi},{id:'airtime',label:'Airtime Card',icon:Smartphone}] as const).map(x=><button key={x.id} onClick={()=>setKind(x.id)} className={`rounded-xl border-2 p-4 text-left ${kind===x.id?'border-emerald-500 bg-emerald-50':'border-border'}`}><x.icon className="h-5 w-5 text-emerald-600"/><b className="mt-2 block">{x.label}</b></button>)}</div><h2 className="mt-6 font-bold">Network</h2><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{networks.map(n=><button key={n.name} onClick={()=>setNetwork(n.name)} className={`rounded-xl border-2 p-3 ${network===n.name?'border-emerald-500 bg-emerald-50':'border-border'}`}><ServiceLogo name={n.name}/><span className="mt-1 block text-xs font-bold">{n.name}</span></button>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Card value<input type="number" min="50" value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-2 w-full rounded-lg border p-3"/></label><label className="text-sm font-semibold">Quantity<input type="number" min="1" max="500" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="mt-2 w-full rounded-lg border p-3"/></label></div></Card><Card padding="lg"><Printer className="h-8 w-8 text-emerald-600"/><h2 className="mt-3 font-bold">Batch summary</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span>Type</span><b className="capitalize">{kind} card</b></div><div className="flex justify-between"><span>Network</span><b>{network}</b></div><div className="flex justify-between"><span>Quantity</span><b>{quantity}</b></div><div className="flex justify-between"><span>Face value</span><b>{naira(value)}</b></div></div><Button fullWidth disabled={saving||quantity<1||value<=0} onClick={()=>void submit()} className="mt-5">{saving?'Saving…':user?'Save voucher batch request':'Sign in to save request'}</Button>{notice&&<p className="mt-3 text-xs font-semibold">{notice}</p>}<p className="mt-3 text-xs text-muted">The final production flow will generate provider-authorized codes, printable sheets and batch records. No placeholder PINs are generated.</p></Card></div>
 </div></PageShell>;
}
