import { useCallback, useEffect, useState } from 'react';
import { DashboardLayout, type SidebarSection } from '@/components/Sidebar';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { StatCard, AnimatedCounter } from '@/components/ui/Charts';
import { naira } from '@/lib/designTokens';
import { TrendingUp, Users, DollarSign, Gift, ShoppingCart, RefreshCw, ReceiptText, ArrowUpCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';

const sidebarSections:SidebarSection[]=[{title:'Reseller',items:[{label:'Dashboard',href:'/datasub/reseller-dashboard',icon:<TrendingUp className="w-4 h-4"/>},{label:'Purchase',href:'/datasub/buy-airtime',icon:<ShoppingCart className="w-4 h-4"/>},{label:'Transactions',href:'/datasub/transactions',icon:<DollarSign className="w-4 h-4"/>},{label:'Upgrade access',href:'/datasub/upgrade',icon:<ArrowUpCircle className="w-4 h-4"/>}]}];
type Account={business_name:string;phone:string;tier_code:string;status:string;total_sales:number;total_profit:number};type Tier={code:string;name:string;minimum_monthly_sales:number;discount_percent:number;api_access:boolean};type Price={id:string;internal_plan_id:string|null;name:string;provider:string;service_type:string;reseller_price:number;retail_price:number}; type CustomPrice={product_id:string;reseller_plan_id:string;selling_price:number;is_active:boolean};
type Commission={id:string;transaction_id:string;sale_amount:number;commission_amount:number;tier_code:string;calculation_basis:string;created_at:string};
export function DataSubResellerDashboard(){
 const {user,profile}=useAuth();const [account,setAccount]=useState<Account|null>(null),[tiers,setTiers]=useState<Tier[]>([]),[prices,setPrices]=useState<Price[]>([]),[customPrices,setCustomPrices]=useState<CustomPrice[]>([]),[commissions,setCommissions]=useState<Commission[]>([]),[businessName,setBusinessName]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[planSearch,setPlanSearch]=useState(''),[commissionSearch,setCommissionSearch]=useState('');
 const load=useCallback(async()=>{if(!supabase||!user)return;const [a,t,p,cp,c]=await Promise.all([supabase.from('datasub_reseller_accounts').select('business_name,phone,tier_code,status,total_sales,total_profit').eq('user_id',user.id).maybeSingle(),supabase.from('datasub_reseller_tiers').select('code,name,minimum_monthly_sales,discount_percent,api_access').eq('is_active',true).order('sort_order'),supabase.from('datasub_products').select('id,internal_plan_id,name,provider,service_type,reseller_price,retail_price').eq('is_active',true).order('provider'),supabase.from('datasub_reseller_product_prices').select('product_id,reseller_plan_id,selling_price,is_active').eq('reseller_user_id',user.id),supabase.from('datasub_reseller_commissions').select('id,transaction_id,sale_amount,commission_amount,tier_code,calculation_basis,created_at').eq('reseller_user_id',user.id).order('created_at',{ascending:false}).limit(20)]);setError(a.error?.message||t.error?.message||p.error?.message||cp.error?.message||c.error?.message||null);setAccount(a.data?{...a.data,total_sales:Number(a.data.total_sales),total_profit:Number(a.data.total_profit)}:null);setTiers((t.data||[]).map(x=>({...x,minimum_monthly_sales:Number(x.minimum_monthly_sales),discount_percent:Number(x.discount_percent)})));setPrices((p.data||[]).map(x=>({...x,reseller_price:Number(x.reseller_price),retail_price:Number(x.retail_price)})));setCustomPrices((cp.data||[]).map(x=>({...x,selling_price:Number(x.selling_price)})));setCommissions((c.data||[]).map(x=>({...x,sale_amount:Number(x.sale_amount),commission_amount:Number(x.commission_amount)})));},[user]);useEffect(()=>{void load();},[load]);
 const userName=profile?[profile.first_name,profile.last_name].filter(Boolean).join(' ')||profile.email:'IHLink Customer';const tier=tiers.find(x=>x.code===account?.tier_code);
 async function saveCustomPrice(product:Price,resellerPlanId:string,sellingPrice:number,isActive=true){if(!supabase||!user||account?.status!=='active')return;setBusy(true);setError(null);const floor=product.reseller_price;if(!Number.isFinite(sellingPrice)||sellingPrice<floor){setError(`Your selling price for ${product.name} cannot be below your IHLink reseller cost of ${naira(floor)}.`);setBusy(false);return;}const planId=resellerPlanId.trim()||`${product.internal_plan_id||product.id.slice(0,8)}-${user.id.slice(0,6)}`;const {error:e}=await supabase.from('datasub_reseller_product_prices').upsert({reseller_user_id:user.id,product_id:product.id,reseller_plan_id:planId,selling_price:sellingPrice,is_active:isActive,updated_at:new Date().toISOString()},{onConflict:'reseller_user_id,product_id'});setBusy(false);if(e)setError(e.message);else{setMessage('Your customer price and reseller plan ID were saved.');await load();}}
 async function apply(){if(!supabase||!user)return;if(businessName.trim().length<2||phone.trim().length<7){setError('Enter a valid business name and phone number.');return;}setBusy(true);setError(null);const {error:e}=await supabase.from('datasub_reseller_accounts').insert({user_id:user.id,business_name:businessName.trim(),phone:phone.trim(),tier_code:'bronze',status:'pending'});setBusy(false);if(e)setError(e.message);else{setMessage('Your reseller application has been submitted for approval.');await load();}}
 return <DashboardLayout product="datasub" sections={sidebarSections} userName={userName} userRole={account?.status==='active'?`${tier?.name||'Bronze'} Reseller`:'Smart Earner'} pageTitle="Reseller Dashboard" pageBreadcrumb={[{label:'Overview'}]}>
  {(error||message)&&<div className={`mb-5 rounded-xl border p-3 text-sm ${error?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||message}</div>}
  {!account?<Card padding="lg" className="mx-auto max-w-2xl"><h2 className="text-2xl font-extrabold">Apply to become an IHLink reseller</h2><p className="mt-2 text-sm text-muted">Submit your business details. DataSub administrators will review your application and assign a pricing tier.</p><div className="mt-6 space-y-3"><input value={businessName} onChange={e=>setBusinessName(e.target.value)} placeholder="Business name" className="w-full rounded-xl border p-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Business phone number" className="w-full rounded-xl border p-3"/><Button disabled={busy} onClick={()=>void apply()}>{busy?'Submitting…':'Submit reseller application'}</Button></div></Card>:<>
   <Card padding="lg" className={`mb-6 border-0 text-white ${account.status==='active'?'bg-gradient-to-br from-amber-400 to-emerald-500':'bg-gradient-to-br from-slate-600 to-slate-800'}`}><div className="flex flex-wrap items-center justify-between gap-4"><div><Badge className="mb-2 bg-white/20 text-white">{account.status.toUpperCase()}</Badge><p className="text-2xl font-extrabold">{account.business_name}</p><p className="mt-1 text-sm text-white/80">{tier?.name||account.tier_code} tier · {tier?.discount_percent||0}% discount</p></div><div className="flex gap-2"><Link to="/datasub/upgrade"><Button variant="secondary" size="sm" leftIcon={<ArrowUpCircle className="h-4 w-4"/>}>Upgrade</Button></Link><Button variant="secondary" size="sm" leftIcon={<RefreshCw className="h-4 w-4"/>} onClick={()=>void load()}>Refresh</Button></div></div></Card>
   <div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Total Sales" value={<AnimatedCounter value={account.total_sales} prefix="₦"/>} icon={<TrendingUp className="h-5 w-5"/>}/><StatCard label="Total Profit" value={<AnimatedCounter value={account.total_profit} prefix="₦"/>} icon={<DollarSign className="h-5 w-5"/>}/><StatCard label="Discount" value={`${tier?.discount_percent||0}%`} icon={<Gift className="h-5 w-5"/>}/><StatCard label="API Access" value={tier?.api_access?'Enabled':'Not included'} icon={<Users className="h-5 w-5"/>}/></div>
   <Card padding="none" className="overflow-hidden"><div className="border-b p-5"><h3 className="font-bold">Your reseller catalogue & customer prices</h3><p className="text-sm text-muted">IHLink sets your reseller cost. You can assign your own plan ID and customer selling price without changing the upstream provider mapping.</p><input type="search" aria-label="Search reseller catalogue" placeholder="Search product, service or provider" value={planSearch} onChange={e=>setPlanSearch(e.target.value)} className="mt-3 w-full max-w-sm rounded-lg border p-2 text-sm"/></div><div className="max-h-[70vh] overflow-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-gray-50 text-xs uppercase text-muted"><tr>{["Product","Service","Provider","IHLink Reseller Cost","Your Plan ID","Your Selling Price","Your Margin","Active"].map(h=><th className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{prices.filter(x=>[x.name,x.service_type,x.provider,x.internal_plan_id].join(" ").toLowerCase().includes(planSearch.toLowerCase())).map(x=>{const custom=customPrices.find(p=>p.product_id===x.id);const currentPrice=custom?.selling_price??x.retail_price;return <tr className="border-t" key={x.id}><td className="p-4 font-semibold">{x.name}</td><td className="p-4 capitalize">{x.service_type.replace("_"," ")}</td><td className="p-4">{x.provider}</td><td className="p-4 font-bold text-emerald-700">{naira(x.reseller_price)}</td><td className="p-3"><input id={`plan-${x.id}`} defaultValue={custom?.reseller_plan_id||""} placeholder={x.internal_plan_id||"Your plan ID"} className="w-40 rounded-lg border p-2 font-mono text-xs"/></td><td className="p-3"><input id={`price-${x.id}`} type="number" min={x.reseller_price} step="0.01" defaultValue={currentPrice} className="w-32 rounded-lg border p-2"/></td><td className="p-4 font-semibold">{naira(currentPrice-x.reseller_price)}</td><td className="p-4"><Button size="sm" disabled={busy||account.status!=="active"} onClick={()=>{const plan=(document.getElementById(`plan-${x.id}`) as HTMLInputElement)?.value||"";const price=Number((document.getElementById(`price-${x.id}`) as HTMLInputElement)?.value);void saveCustomPrice(x,plan,price,custom?.is_active??true);}}>Save</Button></td></tr>})}</tbody></table></div></Card>
   <Card padding="none" className="mt-6 overflow-hidden"><div className="flex items-center gap-3 border-b p-5"><ReceiptText className="h-5 w-5 text-emerald-700"/><div><h3 className="font-bold">Commission ledger</h3><p className="text-sm text-muted">Successful reseller and API sales are recorded automatically.</p></div><input type="search" aria-label="Search commissions" placeholder="Search transaction, tier or basis" value={commissionSearch} onChange={e=>setCommissionSearch(e.target.value)} className="ml-auto w-full max-w-xs rounded-lg border p-2 text-sm"/></div><div className="max-h-[70vh] overflow-auto"><table className="w-full min-w-[680px] text-left"><thead className="bg-gray-50 text-xs uppercase text-muted"><tr><th className="p-4">Date</th><th className="p-4">Transaction</th><th className="p-4">Tier</th><th className="p-4">Sale</th><th className="p-4">Earning</th><th className="p-4">Basis</th></tr></thead><tbody>{commissions.filter(x=>[x.transaction_id,x.tier_code,x.calculation_basis].join(" ").toLowerCase().includes(commissionSearch.toLowerCase())).map(x=><tr className="border-t" key={x.id}><td className="p-4 text-sm">{new Date(x.created_at).toLocaleDateString('en-NG')}</td><td className="p-4 font-mono text-xs">{x.transaction_id.slice(0,8)}…</td><td className="p-4 capitalize">{x.tier_code}</td><td className="p-4 font-semibold">{naira(x.sale_amount)}</td><td className="p-4 font-bold text-emerald-700">{naira(x.commission_amount)}</td><td className="p-4 text-sm capitalize">{x.calculation_basis.replace('_',' ')}</td></tr>)}{!commissions.length&&<tr><td colSpan={6} className="p-10 text-center text-sm text-muted">Your successful reseller sales will appear here.</td></tr>}</tbody></table></div></Card>
  </>}
 </DashboardLayout>;
}
