import {SavedRecipients} from '@/components/SavedRecipients';
import {useEffect,useState} from 'react';import {DashboardLayout,type SidebarSection} from '@/components/Sidebar';import {Card} from '@/components/ui/Card';import {Button} from '@/components/ui/Button';import {useAuth} from '@/context/AuthContext';import {supabase} from '@/lib/supabase';import {Heart,ShieldCheck,Users,CalendarClock} from 'lucide-react';import{useDataSubTier}from'@/hooks/useDataSubTier';
const sections:SidebarSection[]=[{title:'Customer',items:[{label:'Dashboard',href:'/datasub/dashboard',icon:<Users className="h-4 w-4"/>},{label:'Customer Tools',href:'/datasub/customer-tools',icon:<ShieldCheck className="h-4 w-4"/>}]}];
export function DataSubCustomerTools(){const {user,profile}=useAuth();const{tier}=useDataSubTier();const [beneficiaries,setBeneficiaries]=useState<any[]>([]),[favourites,setFavourites]=useState<any[]>([]),[schedules,setSchedules]=useState<any[]>([]),[disputes,setDisputes]=useState<any[]>([]),[daily,setDaily]=useState(''),[monthly,setMonthly]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState('');
async function load(){if(!supabase||!user)return;const [b,f,s,d,l]=await Promise.all([supabase.from('datasub_beneficiaries').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),supabase.from('datasub_favourites').select('id,label,created_at,datasub_catalog_offerings(name,service_type,network)').eq('user_id',user.id).order('created_at',{ascending:false}),supabase.from('datasub_scheduled_purchases').select('id,recipient,frequency,next_run_at,active,datasub_catalog_offerings(name)').eq('user_id',user.id).order('next_run_at'),supabase.from('datasub_disputes').select('id,category,status,details,created_at').eq('user_id',user.id).order('created_at',{ascending:false}),supabase.from('datasub_spending_limits').select('daily_limit,monthly_limit').eq('user_id',user.id).maybeSingle()]);setBeneficiaries(b.data||[]);setFavourites(f.data||[]);setSchedules(s.data||[]);setDisputes(d.data||[]);if(l.data){setDaily(String(l.data.daily_limit||''));setMonthly(String(l.data.monthly_limit||''));}}
useEffect(()=>{void load()},[user]);
async function saveLimits(){if(!supabase||!user)return;const {error}=await supabase.from('datasub_spending_limits').upsert({user_id:user.id,daily_limit:daily?Number(daily):null,monthly_limit:monthly?Number(monthly):null,updated_at:new Date().toISOString()},{onConflict:'user_id'});setNotice(error?'Your spending limits could not be saved. Please try again.':'Spending limits saved.');}
const name=profile?[profile.first_name,profile.last_name].filter(Boolean).join(' ')||profile.email:'Smart Earner';const roleLabel=tier==='api_user'?'API User':tier==='top_seller'?'Top Seller':tier==='reseller'?'Reseller':'Smart Earner';
const match=(x:any)=>!search||JSON.stringify(x).toLowerCase().includes(search.toLowerCase());
return <DashboardLayout product="datasub" sections={sections} userName={name} userRole={roleLabel} pageTitle="Customer Tools"><div className="mb-5"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search beneficiaries, favourites, schedules and disputes…" className="w-full rounded-xl border p-3 text-sm"/></div><div className="grid gap-5 lg:grid-cols-2"><div className="lg:col-span-2"><SavedRecipients/></div><Card><h3 className="font-bold flex gap-2"><CalendarClock className="h-5 w-5"/>Scheduled Purchases</h3><div className="mt-3 space-y-2">{schedules.filter(match).map(x=><div key={x.id} className="rounded-lg border p-3 text-sm"><b>{x.datasub_catalog_offerings?.name||'Service'}</b><p className="text-muted">{x.recipient} · {x.frequency} · {new Date(x.next_run_at).toLocaleString('en-NG')}</p></div>)}{!schedules.length&&<p className="text-sm text-muted">No scheduled purchases.</p>}</div></Card><Card><h3 className="font-bold flex gap-2"><ShieldCheck className="h-5 w-5"/>Spending Controls</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><input type="number" value={daily} onChange={e=>setDaily(e.target.value)} placeholder="Daily limit (₦)" className="rounded-lg border p-2.5"/><input type="number" value={monthly} onChange={e=>setMonthly(e.target.value)} placeholder="Monthly limit (₦)" className="rounded-lg border p-2.5"/></div><Button className="mt-3" onClick={()=>void saveLimits()}>Save limits</Button>{notice&&<p className="mt-2 text-sm text-muted">{notice}</p>}</Card><Card className="lg:col-span-2"><h3 className="font-bold">Dispute & Resolution Centre</h3><div className="mt-3 grid gap-2 md:grid-cols-2">{disputes.filter(match).map(x=><div key={x.id} className="rounded-lg border p-3 text-sm"><b>{x.category}</b><p>{x.details}</p><p className="mt-1 text-xs text-muted">{x.status} · {new Date(x.created_at).toLocaleDateString('en-NG')}</p></div>)}{!disputes.length&&<p className="text-sm text-muted">No disputes raised.</p>}</div></Card></div></DashboardLayout>}