import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, Check, Code, Copy, Key, Loader2, Plus, Shield, Trash2 } from 'lucide-react';
import { DashboardLayout, type SidebarSection } from '@/components/Sidebar';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { StatCard, AnimatedCounter } from '@/components/ui/Charts';
import { useToast } from '@/components/ui/Toast';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { formatDateTime } from '@/lib/designTokens';

const sidebarSections: SidebarSection[] = [{ title: 'API', items: [
  { label: 'Dashboard', href: '/datasub/api-dashboard', icon: <Activity className="w-4 h-4" /> },
  { label: 'Documentation', href: '/datasub/api', icon: <Code className="w-4 h-4" /> },
]}];

type Credential={id:string;label:string;key_prefix:string;mode:'sandbox'|'live';status:'active'|'revoked';last_used_at:string|null;created_at:string};
type Usage={id:number;credential_id:string;endpoint:string;method:string;status_code:number;response_ms:number;request_units:number;created_at:string};
type Reseller={status:string;tier_code:string};
const friendlyError=(message?:string)=>message?.includes('API-enabled reseller tier')?'An active API-enabled reseller tier is required.':message?.includes('five active API keys')?'You already have the maximum of five active API keys.':message?.includes('Label must')?'Enter a credential label containing at least two characters.':'We could not complete the API request. Please refresh and try again.';

export function DataSubApiDashboard(){
 const {user,profile}=useAuth(); const {showToast}=useToast();
 const [credentials,setCredentials]=useState<Credential[]>([]),[usage,setUsage]=useState<Usage[]>([]),[reseller,setReseller]=useState<Reseller|null>(null),[apiAccess,setApiAccess]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[label,setLabel]=useState('Primary integration'),[mode,setMode]=useState<'sandbox'|'live'>('sandbox'),[newSecret,setNewSecret]=useState<string|null>(null),[credentialSearch,setCredentialSearch]=useState('');
 const load=useCallback(async()=>{if(!supabase||!user)return;setLoading(true);setError(null);const account=await supabase.from('datasub_reseller_accounts').select('status,tier_code').eq('user_id',user.id).maybeSingle();let allowed=false;if(account.data){const tier=await supabase.from('datasub_reseller_tiers').select('api_access').eq('code',account.data.tier_code).maybeSingle();allowed=account.data.status==='active'&&Boolean(tier.data?.api_access);setApiAccess(allowed);}else setApiAccess(false);const [keys,calls]=await Promise.all([supabase.from('datasub_api_credentials').select('id,label,key_prefix,mode,status,last_used_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false}),supabase.from('datasub_api_usage').select('id,credential_id,endpoint,method,status_code,response_ms,request_units,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)]);const first=account.error||keys.error||calls.error;if(first)setError(friendlyError());setReseller(account.data as Reseller|null);setCredentials((keys.data||[]) as Credential[]);setUsage((calls.data||[]) as Usage[]);setLoading(false);},[user]);
 useEffect(()=>{void load();},[load]);
 const active=credentials.filter(x=>x.status==='active'),totalUnits=usage.reduce((s,x)=>s+x.request_units,0),successful=usage.filter(x=>x.status_code>=200&&x.status_code<300).length,successRate=usage.length?`${((successful/usage.length)*100).toFixed(1)}%`:'—',averageMs=usage.length?`${Math.round(usage.reduce((s,x)=>s+x.response_ms,0)/usage.length)}ms`:'—',keyMap=useMemo(()=>new Map(credentials.map(x=>[x.id,x.label])),[credentials]),userName=profile?[profile.first_name,profile.last_name].filter(Boolean).join(' ')||profile.email:'API Developer';
 async function generate(){if(!supabase)return;setBusy(true);setError(null);setNewSecret(null);const {data,error:e}=await supabase.rpc('create_datasub_api_credential',{p_label:label.trim(),p_mode:mode});setBusy(false);if(e){setError(friendlyError(e.message));return;}setNewSecret((data as {secret:string}).secret);showToast('success','API key created','Copy it now. It will not be displayed again.');await load();}
 async function revoke(id:string){if(!supabase)return;setBusy(true);const {error:e}=await supabase.rpc('revoke_datasub_api_credential',{p_credential_id:id});setBusy(false);if(e)setError(friendlyError(e.message));else{showToast('success','API key revoked','Requests using this key will be rejected.');await load();}}
 async function copySecret(){if(!newSecret)return;await navigator.clipboard.writeText(newSecret);showToast('info','Copied','The API key was copied to your clipboard.');}
 return <DashboardLayout product="datasub" sections={sidebarSections} userName={userName} userRole="API Developer" pageTitle="API Dashboard" pageBreadcrumb={[{label:'Overview'}]}>
  {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Request units (100 latest)" value={<AnimatedCounter value={totalUnits}/>} icon={<Activity className="h-5 w-5"/>} iconBg="bg-emerald-50" iconColor="text-emerald-600"/><StatCard label="Success rate" value={successRate} icon={<Shield className="h-5 w-5"/>} iconBg="bg-sky-50" iconColor="text-sky-600"/><StatCard label="Average response" value={averageMs} icon={<Activity className="h-5 w-5"/>} iconBg="bg-amber-50" iconColor="text-amber-600"/><StatCard label="Active keys" value={String(active.length)} icon={<Key className="h-5 w-5"/>} iconBg="bg-purple-50" iconColor="text-purple-600"/></div>
  {!apiAccess&&<Card padding="lg" className="mb-6 border-amber-200 bg-amber-50"><h3 className="font-bold text-amber-900">API access is not active</h3><p className="mt-1 text-sm text-amber-800">{!reseller?'Apply for a reseller account first.':reseller.status!=='active'?'Your reseller application must be approved first.':'Your current reseller tier does not include API access. Contact a DataSub administrator for an API-enabled tier.'}</p></Card>}
  <div className="grid grid-cols-12 gap-6"><div className="col-span-12 lg:col-span-7"><Card padding="lg" className="mb-6"><h3 className="text-lg font-bold">Create API credential</h3><p className="mt-1 text-sm text-muted">Secrets are generated securely and stored only as a SHA-256 hash. Each secret is shown once.</p><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_150px_auto]"><input value={label} onChange={e=>setLabel(e.target.value)} maxLength={60} className="rounded-xl border px-3 py-2" placeholder="Credential label"/><select value={mode} onChange={e=>setMode(e.target.value as 'sandbox'|'live')} className="rounded-xl border px-3 py-2"><option value="sandbox">Sandbox</option><option value="live">Live</option></select><Button disabled={!apiAccess||busy||label.trim().length<2} leftIcon={busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>} onClick={()=>void generate()}>Generate</Button></div>{newSecret&&<div className="mt-4 rounded-xl bg-navy-900 p-4"><div className="flex items-center gap-3"><Check className="h-5 w-5 text-emerald-400"/><code className="min-w-0 flex-1 break-all text-sm text-emerald-300">{newSecret}</code><button onClick={()=>void copySecret()} aria-label="Copy new API key" className="rounded-lg p-2 text-emerald-300 hover:bg-white/10"><Copy className="h-4 w-4"/></button></div><p className="mt-2 text-xs text-slate-300">Save this key now. It cannot be recovered after you leave this page.</p></div>}</Card>
  <Card padding="none" className="overflow-hidden"><div className="border-b p-5"><h3 className="font-bold">Credentials</h3><input type="search" aria-label="Search credentials" placeholder="Search credentials" value={credentialSearch} onChange={e=>setCredentialSearch(e.target.value)} className="mt-3 w-full max-w-sm rounded-lg border p-2 text-sm"/></div>{loading?<div className="flex items-center gap-2 p-8 text-muted"><Loader2 className="h-5 w-5 animate-spin"/>Loading…</div>:<div className="max-h-[70vh] overflow-auto"><table className="w-full min-w-[650px] text-left"><thead className="bg-gray-50 text-xs uppercase text-muted"><tr>{['Label','Prefix','Mode','Status','Created','Action'].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{credentials.filter(x=>[x.label,x.key_prefix,x.mode,x.status].join(" ").toLowerCase().includes(credentialSearch.toLowerCase())).map(x=><tr key={x.id} className="border-t"><td className="p-4 font-semibold">{x.label}</td><td className="p-4 font-mono text-xs">{x.key_prefix}…</td><td className="p-4 capitalize">{x.mode}</td><td className="p-4"><Badge variant="status" status={x.status}/></td><td className="p-4 text-xs text-muted">{formatDateTime(x.created_at)}</td><td className="p-4">{x.status==='active'?<Button size="sm" variant="secondary" disabled={busy} leftIcon={<Trash2 className="h-4 w-4"/>} onClick={()=>void revoke(x.id)}>Revoke</Button>:<span className="text-xs text-muted">Revoked</span>}</td></tr>)}{!credentials.length&&<tr><td colSpan={6} className="p-10 text-center text-sm text-muted">No API credentials yet.</td></tr>}</tbody></table></div>}</Card></div>
  <div className="col-span-12 lg:col-span-5"><Card padding="none" className="overflow-hidden"><div className="border-b p-5"><h3 className="font-bold">Live request usage</h3><p className="text-sm text-muted">Latest 100 requests recorded by the DataSub API gateway.</p></div><div className="max-h-[620px] overflow-auto">{usage.map(x=><div key={x.id} className="border-b p-4 last:border-0"><div className="flex items-center justify-between gap-3"><code className="text-xs font-semibold">{x.method} {x.endpoint}</code><Badge variant="status" status={x.status_code>=200&&x.status_code<300?'success':'failed'}/></div><div className="mt-2 flex justify-between text-xs text-muted"><span>{keyMap.get(x.credential_id)||'Credential'} · {x.response_ms}ms</span><span>{formatDateTime(x.created_at)}</span></div></div>)}{!usage.length&&<p className="p-10 text-center text-sm text-muted">No API requests have been recorded yet.</p>}</div></Card></div></div>
 </DashboardLayout>;
}
