import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Loader2, Sparkles } from 'lucide-react';
import { PageShell } from '@/components/PageShell';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { naira } from '@/lib/designTokens';

type Offer = { code:string; name:string; description:string; base_price:number; promo_discount_percent:number; promo_starts_at:string|null; promo_ends_at:string|null; api_access:boolean; benefits:string[]; sort_order:number };
const fallbackOffers:Offer[]=[{code:'reseller',name:'Reseller',description:'Reseller pricing, sales tools and dashboard access.',base_price:0,promo_discount_percent:0,promo_starts_at:null,promo_ends_at:null,api_access:false,benefits:['Reseller dashboard','Tier-based pricing','Sales tracking'],sort_order:1},{code:'api_developer',name:'API User',description:'Developer access prepared for server-to-server DataSub integration.',base_price:0,promo_discount_percent:0,promo_starts_at:null,promo_ends_at:null,api_access:true,benefits:['API dashboard','Credential management','Usage tracking'],sort_order:2},{code:'top_seller',name:'Top Seller',description:'Performance tier awarded by IHLink administrators based on reseller performance.',base_price:0,promo_discount_percent:0,promo_starts_at:null,promo_ends_at:null,api_access:true,benefits:['Higher-volume tier','API capability','Reseller analytics'],sort_order:3}];
const customerBenefits=['Free account','Customer catalogue prices','Wallet funding','All bill payments','Transaction history','Email support'];
const promoActive=(offer:Offer)=>{const now=Date.now();return offer.promo_discount_percent>0&&(!offer.promo_starts_at||new Date(offer.promo_starts_at).getTime()<=now)&&(!offer.promo_ends_at||new Date(offer.promo_ends_at).getTime()>=now);};

export function DataSubPricing(){
 const {user}=useAuth();
 const [offers,setOffers]=useState<Offer[]>([]),[loading,setLoading]=useState(true),[requesting,setRequesting]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 useEffect(()=>{async function load(){if(!supabase){setLoading(false);return;}const {data,error:loadError}=await supabase.from('datasub_upgrade_offers').select('code,name,description,base_price,promo_discount_percent,promo_starts_at,promo_ends_at,api_access,benefits,sort_order').eq('is_active',true).order('sort_order');if(loadError)setError('Pricing could not be loaded. Please try again shortly.');const loaded=((data||[]).map(row=>({...row,base_price:Number(row.base_price),promo_discount_percent:Number(row.promo_discount_percent),benefits:Array.isArray(row.benefits)?row.benefits:[]})) as Offer[]);setOffers(loaded.length?loaded:fallbackOffers);setLoading(false);}void load();},[]);
 const cards=useMemo(()=>offers.map(offer=>{const active=promoActive(offer);return {...offer,activePromo:active,payable:active?offer.base_price*(1-offer.promo_discount_percent/100):offer.base_price};}),[offers]);
 async function requestUpgrade(offer:(typeof cards)[number]){if(!supabase||!user)return;setRequesting(offer.code);setMessage(null);setError(null);const {error:requestError}=await supabase.from('datasub_upgrade_requests').insert({user_id:user.id,offer_code:offer.code,quoted_price:offer.payable});setRequesting(null);if(requestError)setError(requestError.code==='23505'?'You already have a pending request for this upgrade.':'Your upgrade request could not be submitted. Please try again.');else setMessage(`${offer.name} upgrade requested. DataSub Operations will review it.`);}
 return <PageShell product="datasub"><section className="mx-auto max-w-[1280px] px-6 py-16 lg:px-10"><div className="mb-10 text-center"><Badge className="mb-3 border-emerald-200 bg-emerald-50 text-emerald-700">Upgrade options</Badge><h1 className="mb-3 text-4xl font-extrabold text-ink">Choose how you use IHLink DataSub</h1><p className="mx-auto max-w-2xl text-base text-muted">Upgrade options remain visible while production pricing is configured. Live prices and promotions are controlled by DataSub Operations.</p></div>
 {(message||error)&&<div className={`mx-auto mb-6 max-w-3xl rounded-xl border p-4 text-sm ${error?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||message}</div>}
 <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4"><Card padding="lg"><h3 className="text-xl font-bold text-ink">Smart Earner</h3><p className="mb-4 text-sm text-muted">Normal DataSub customer</p><p className="mb-1 text-4xl font-extrabold text-ink">Free</p><p className="mb-6 text-xs text-muted">No upgrade fee</p><Link to="/register"><Button fullWidth variant="secondary">Sign Up Free</Button></Link><div className="mt-6 space-y-3">{customerBenefits.map(item=><div key={item} className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 shrink-0 text-emerald-500"/>{item}</div>)}</div></Card>
 {loading?<Card padding="lg" className="grid min-h-80 place-items-center md:col-span-2 xl:col-span-3"><Loader2 className="h-7 w-7 animate-spin text-emerald-600"/></Card>:cards.map((offer,index)=><Card key={offer.code} padding="lg" className={`relative ${index===0?'border-2 border-emerald-400 shadow-float':''}`}>{offer.activePromo&&<Badge className="absolute right-4 top-4 border-amber-200 bg-amber-50 text-amber-700"><Sparkles className="mr-1 h-3 w-3"/>{offer.promo_discount_percent}% promo</Badge>}<h3 className="pr-24 text-xl font-bold text-ink">{offer.name}</h3><p className="mb-4 text-sm text-muted">{offer.description}</p>{offer.activePromo&&<p className="text-sm text-muted line-through">{naira(offer.base_price)}</p>}{offer.code==='reseller'?<><p className="mb-1 text-4xl font-extrabold text-ink">{naira(offer.payable)}</p><p className="mb-6 text-xs text-muted">one-time branded reseller website setup</p></>:<><p className="mb-1 text-2xl font-extrabold text-ink">{offer.code==='api_developer'?'Request access':'Performance tier'}</p><p className="mb-6 text-xs text-muted">{offer.code==='api_developer'?'No fee · website/application review required':'No price tag · awarded only by an administrator'}</p></>}{!user?<Link to="/signin"><Button fullWidth variant={index===0?undefined:'secondary'}>Sign in to upgrade</Button></Link>:<Button fullWidth disabled={requesting===offer.code} variant={index===0?undefined:'secondary'} onClick={()=>offer.code==='top_seller'?setMessage('Top Seller status is awarded only by IHLink administrators based on performance.'):void requestUpgrade(offer)}>{requesting===offer.code?'Submitting…':offer.code==='top_seller'?'Performance-awarded':`Request ${offer.name}`}</Button>}<div className="mt-6 space-y-3">{offer.benefits.map(item=><div key={item} className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 shrink-0 text-emerald-500"/>{item}</div>)}</div></Card>)}</div>
 <div className="mt-12 text-center"><p className="mb-4 text-sm text-muted">DataSub Operations can start, stop or change promotions without changing the website code.</p><Link to="/datasub/reseller"><Button variant="secondary" rightIcon={<ArrowRight className="h-4 w-4"/>}>Compare reseller benefits</Button></Link></div></section></PageShell>;
}
